apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    app.kubernetes.io/instance: sampleapp
  name: nginx-svc
  namespace: firstargo2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
status:
  loadBalancer: {}
